[package]
name = "adyton_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.8.2"
openzeppelin_token = "0.19.0"
openzeppelin_access = "0.19.0"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
